avito_login: YOUR_AVITO_LOGIN
avito_pass: YOUR_AVITO_PASS
smtp_host: YOUR_SMTP_HOST
smtp_port: YOUR_SMTP_PORT
smtp_login: YOUR_SMTP_LOGIN
smtp_pass: YOUR_SMTP_PASS
email_from: EMAIL_FROM
email_to: EMAIL_TO
